//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriaweb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleados()
        {
            this.facturas = new HashSet<facturas>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Ingresar nombre")]
        [StringLength(100)]
        public string nombre { get; set; }
        [Required]
        [RegularExpression("^\\d{3}-?\\d{7}-?[0-9]$", ErrorMessage ="Cedula invalida")]
        public string cedula { get; set; }
        public string tanda_labor { get; set; }
        public int porciento_comision { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturas> facturas { get; set; }
    }
}
