//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriaweb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class facturas
    {
        public int id { get; set; }
        public int id_empleado { get; set; }
        public int id_articulo { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public decimal monto_articulo { get; set; }
        public int cantidad { get; set; }
        public string comentario { get; set; }
        public bool estado { get; set; }
    
        public virtual articulos articulos { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
