//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriaweb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.facturas = new HashSet<facturas>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage="Ingresar nombre.")]
        public string nombre { get; set; }
        [Required]
        [RegularExpression("^\\d{3}-?\\d{7}-?[0-9]$", ErrorMessage = "Cedula invalida")]
        public string cedula { get; set; }
        public int id_tipo { get; set; }
        public decimal limite_credito { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturas> facturas { get; set; }
        public virtual tipos_usuario tipos_usuario { get; set; }
    }
}
